server:
  port: 8180
spring:
  application:
    name: service-statistic
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath*:com/kk/service/statistic/mapper/*.xml
  type-aliases-package: com.kk.service.statistic.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
    table-prefix: statistic_
