server:
  port: 9110
spring:
  application:
    name: infrastructure-apigateway
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.56.1:8848
    gateway:
      routes:
        - id: service-edu
          uri: lb://service-edu
          predicates:
           - Path=/user/**, /*/edu/**
        - id: service-cms
          uri: lb://service-cms
          predicates:
            - Path=/*/cms/**
        - id: service-oss
          uri: lb://service-oss
          predicates:
            - Path=/*/oss/**
        - id: service-sms
          uri: lb://service-sms
          predicates:
            - Path=/*/sms/**
        - id: service-trade
          uri: lb://service-trade
          predicates:
            - Path=/*/trade/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/*/ucenter/**
        - id: service-vod
          uri: lb://service-vod
          predicates:
            - Path=/*/vod/**
        - id: service-statistic
          uri: lb://service-statistic
          predicates:
            - Path=/*/statistic/**
      discovery:
        locator:
          enabled: true