server:
  port: 8180
spring:
  application:
    name: service-statistic
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: 192.168.56.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3307/giot_statistic?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:com/kk/service/statistic/mapper/*.xml
  type-aliases-package: com.kk.service.statistic.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: statistic_