server:
  port: 8170
spring:
  application:
    name: service-trade
  redis:
    host: 192.168.56.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      server-addr: 192.168.56.1:8848
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.1:3307/giot_trade?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: trade_
  type-aliases-package: com.kk.service.pojo
  mapper-locations: classpath*:com/kk/service/trade/mapper/*.xml
